### PR TITLE
Update the completions, using the values from the VS Code extension

### PR DESCRIPTION
**Pull request by Release-Candidate**
This adds new completions from the VS Code extension, file https://github.com/xmake-io/xmake-vscode/blob/master/src/completion.ts and https://github.com/xmake-io/xmake-vscode/blob/master/src/commands.ts

I sorted the completions, so that comparisons are easier in the future.

### CODE REVIEW

**Comment by waruqi** [comment]
Thanks, but I've forgotten how to update the plugin to the marketplace. :(

**Comment by Release-Candidate** [comment]
> Thanks, but I've forgotten how to update the plugin to the marketplace. :(

As it is already registered you just need to tag the version and it should get updated automatically soon.

**Comment by waruqi** [comment]
ok, I have updated tag

**Comment by Release-Candidate** [comment]
It worked, the package is now the latest version: https://packagecontrol.io/packages/xmake

**Pull request merged**
